### PR TITLE
submitted my mail address

### PR DESCRIPTION
**Pull request by RebeccaDiP**

### CODE REVIEW

**Review by vogti — CHANGES_REQUESTED** [review]
The hash seems to be unknown. Did you use your university mail address?

**Comment by RebeccaDiP** [comment]
> The hash seems to be unknown. Did you use your university mail address?

I did. This account is set up through my private mail address but I entered my university mail account when I called the bash file. Should I try again by opening a new GitHub account with the right mail address?

**Comment by vogti** [comment]
The mail address used for your GitHub account has no impact. So this is fine. You’ve probably had a typo in your mail address. I have just checked and calculated the hash for your University mail address (your GitHub username was unique enough to identify you in the list of enrollments :D). Your hash should start with "7744ae5e83bce...". Best thing is to delete the file you have created and then execute the submit script again. Just in case you have recently switched from a @stud.unibas.ch to an @unibas.ch mail address: When I have created the hashes for the verification scripts, you have been listed with a  @stud.unibas.ch. So please use this address. After executing the submit script again, simply commit and push  your changes to GitHub. This will automatically update the Pull Request.

**Comment by RebeccaDiP** [comment]
> The mail address used for your GitHub account has no impact. So this is fine. You’ve probably had a typo in your mail address. I have just checked and calculated the hash for your University mail address (your GitHub username was unique enough to identify you in the list of enrollments :D). Your hash should start with "7744ae5e83bce...". Best thing is to delete the file you have created and then execute the submit script again. Just in case you have recently switched from a @stud.unibas.ch to an @unibas.ch mail address: When I have created the hashes for the verification scripts, you have been listed with a @stud.unibas.ch. So please use this address. After executing the submit script again, simply commit and push your changes to GitHub. This will automatically update the Pull Request.

Got it, thank you very much for the assistance and help. I just deleted the file as you suggested and tried to run the submit script again, but it just keeps on creating the same hash file starting with: "138092d8ac2...". I even double-checked the mail address, which is indeed ending with @stud.unibas.ch, but to no avail, it keeps generating the same hash. I'm unsure as to how I should proceed now. (Btw. German is fine too, I just prefer to comment things out in English :) )

**Review by vogti — APPROVED** [review]

**Pull request merged**
